#!/usr/bin/env python

# -----------------------------------------------------------------------
# reg.py
# Author: Edward and Bharat
# -----------------------------------------------------------------------

from os import path
from sys import argv, stderr, exit
from sqlite3 import connect

#import server/socket handling
from sys import exit, argv, stderr
from socket import socket, AF_INET, SOCK_STREAM
from pickle import load

#import GUI widgets
from sys import exit
from PyQt5.QtWidgets import QApplication, QPushButton, QGridLayout
from PyQt5.QtWidgets import QMainWindow, QFrame, QDesktopWidget, QListWidgetItem
from PyQt5.QtWidgets import QLineEdit, QLabel, QListWidget, QMessageBox

# -----------------------------------------------------------------------

def stdStr(row):
    output = str(row[0]) + '  \t' + \
             str(row[1]) + '\t\t' + \
             str(row[2]) + '\t\t' + \
             str(row[3]) + '\t\t' + \
             str(row[4])
    return output


def main(argv):
    app = QApplication([])
    button = QPushButton('Search Courses')
    listWidget = QListWidget()

    LineEdit1 = QLineEdit('')
    LineEdit2 = QLineEdit('')
    LineEdit3 = QLineEdit('')
    LineEdit4 = QLineEdit('')

    deptLabel = QLabel('Department:')
    coursenumLabel = QLabel('Course Num:')
    areaLabel = QLabel('Area:')
    titleLabel = QLabel('Title:')


    outputLayout = QGridLayout()
    outputLayout.setRowStretch(0, 0)
    outputLayout.setColumnStretch(0, 0)
    outputLayout.addWidget(button, 0, 0)
    outputLayout.addWidget(listWidget, 1, 0)
    outputFrame = QFrame()
    outputFrame.setLayout(outputLayout)

    inputLayout = QGridLayout()
    inputLayout.addWidget(deptLabel, 0, 1)
    inputLayout.addWidget(coursenumLabel, 1, 1)
    inputLayout.addWidget(areaLabel, 2, 1)
    inputLayout.addWidget(titleLabel, 3, 1)
    inputLayout.addWidget(LineEdit1, 0, 2)
    inputLayout.addWidget(LineEdit2, 1, 2)
    inputLayout.addWidget(LineEdit3, 2, 2)
    inputLayout.addWidget(LineEdit4, 3, 2)
    inputFrame = QFrame()
    inputFrame.setLayout(inputLayout)

    FrameLayout = QGridLayout()
    FrameLayout.setContentsMargins(0, 0, 0, 0)
    FrameLayout.setRowStretch(0, 1)
    FrameLayout.setColumnStretch(0, 1)
    FrameLayout.addWidget(outputFrame, 0, 0)
    FrameLayout.addWidget(inputFrame, 0, 1)
    Frame = QFrame()
    Frame.setLayout(FrameLayout)

    window = QMainWindow()
    window.setWindowTitle('Search the Course Registrar')
    window.setCentralWidget(Frame)
    screenSize = QDesktopWidget().screenGeometry()
    window.resize(screenSize.width() // 2, screenSize.height() // 2)

    def buttonSlot():
        listWidget.clear()
        args = [argv[0]]
        args.append("-h")
        if LineEdit1.text() != '':
            args.append('-dept')
            args.append(LineEdit1.text())
        if LineEdit2.text() != '':
            args.append('-coursenum')
            args.append(LineEdit2.text())
        if LineEdit3.text() != '':
            args.append('-area')
            args.append(LineEdit3.text())
        if LineEdit4.text() != '':
            args.append('-title')
            args.append(LineEdit4.text())

        output = managedb(args)
        for item in output:
            listWidget.addItem(item)

        def handleClick():
            item = listWidget.currentItem()
            text = item.text()
            itemcoursenum = text[0:text.index('\t')]
            finalStr = regdetails.runDetails(['regdetails', '-h', itemcoursenum])
            reply = QMessageBox.information(window, 'My title', finalStr)

        listWidget.itemActivated.connect(handleClick)
        window.show()

    button.clicked.connect(buttonSlot)
    LineEdit1.returnPressed.connect(buttonSlot)
    LineEdit2.returnPressed.connect(buttonSlot)
    LineEdit3.returnPressed.connect(buttonSlot)
    LineEdit4.returnPressed.connect(buttonSlot)

    window.show()
    exit(app.exec_())


if __name__ == '__main__':
    main(argv)

