#!/usr/bin/env python

# -----------------------------------------------------------------------
# reg.py
# Author: Bob Dondero
# -----------------------------------------------------------------------

from os import path
from sys import argv, stderr, exit
from sqlite3 import connect

# -----------------------------------------------------------------------
print("reached here")

def main(argv):
    DATABASE_NAME = 'reg.sqlite'

    if len(argv) != 2:
        print("Usage: python reg title", file=stderr)
        exit(1)

    roomnum = argv[1]

    if not path.isfile(DATABASE_NAME):
        raise Exception('Database connection failed')

    connection = connect(DATABASE_NAME)
    cursor = connection.cursor()

    # Create a prepared statement and substitute values.
    stmtStr = 'SELECT roomnum, area, title ' + \
              'FROM classes, courses ' + \
              'WHERE classes.courseid = courses.courseid ' + \
              'AND roomnum = ?'
    cursor.execute(stmtStr, [roomnum])

    row = cursor.fetchone()
    while row is not None:
        print('Class day of the week:', str(row[0]))
        print('Class Title:', str(row[1]))
        print('Quantity:', str(row[2]))
        print()
        row = cursor.fetchone()

    cursor.close()
    connection.close()

if __name__ == '__main__':
    main(argv)