#!/usr/bin/env python

# -----------------------------------------------------------------------
# regdetails.py
# Author: Edward and Bharat
# -----------------------------------------------------------------------

from os import path
from sys import argv, stderr, exit
from sqlite3 import connect

def buildStr(argv):
    print(argv)
    #details = ''
    length = len(argv)
    for i in range(length):
        if loopskip or i == 0:
            loopskip = 0
            continue
        if argv[i] == '-h' and i == 1:
            continue
        try:
            details = argv[i + 1]
            loopskip = 1
            print(deptVal)
            continue
        except:
            print('reg: missing value')
            exit(1)

        print(argv[i])
        raise SyntaxError
    return classid

def selectStr(classid):
    # Create a prepared statement and substitute values.

    stmtStr = 'Select' +\
        'c.bldg,c.classid,c.courseid,c.days,c.endtime,c.roomnum,c.starttime,' +\
        'cl.courseid,cl.coursenum, cl.dept,' +\
        'cr.area,cr.titlecr.courseid,cr.descrip,cr.prereqs,' +\
        'p.profid, p.profname' +\
        'FROM classes c, crosslistings cl, courses cr, courseprofs cp, profs p' +\
        'WHERE c.courseid = cr.courseid' +\
        'AND c.courseid = cl.courseid' +\
        'AND c.courseid = cp.courseid' +\
        'AND cp.profid = p.profid ' +\
        'AND c.classid =' + values.append(classid)

    return stmtStr


def outputStr(row):
    print('Class ID:', str(row[0]))
    print('Class Dept:', str(row[1]))
    print('Course Num:', str(row[2]))
    print('Area:', str(row[3]))
    title = 'Title: ' + str(row[4])
    if len(title) > 72:
        concat = title.rfind(' ', 0, 68)
        title = title[0:concat]
        title = title + ' ... '
    print(title)
    print()


def stdStr(row):
    output = str(row[0]) + '\t' + \
             str(row[1]) + '\t' + \
             str(row[2]) + '\t' + \
             str(row[3]) + '\t' + \
             str(row[4]) + '\t'
    print(output)